### PR TITLE
Added manpage for build-recorder.

### LINKED ISSUE #184: Missing man page
There should be  a man page for the command-line utility.

### PR DESCRIPTION
**Pull request by fvalasiad**
Closes #184.

### CODE REVIEW

**Comment by zvr** [comment]
What kind of macros are you using? They don't look like the traditional `an` ones...

**Comment by fvalasiad** [comment]
Well well I didn't pick macros from a certain version but I am fine with the idea of doing so. Just give me a pointer so I known what to update.

**Comment by fvalasiad** [comment]
@zvr Well after looking around I noticed I was using some `mdoc(7)` macros from BSD. Replaced em with their man(7) equivalents, that's what you meant?

**Comment by zvr** [comment]
I'm merging this and we can improve later (missing OPTIONS section, empty lines, etc.).

**Pull request merged**
