### PR TITLE
Generate test/Makefile from test/Makefile.am with autoconf.

### LINKED ISSUE #185: Tests makefile integration
Currently tests (in the `test`) subdirectory use a custom-written `Makefile`. This should be replaced by an appropriate `Makefile.am` and integrated with `autoconf`.

### PR DESCRIPTION
**Pull request by fvalasiad**
Closes #185.

### CODE REVIEW

**Comment by zvr** [comment]
Eh, no. The desired outcome is not to simply copy the hand-crafted rules.
It should be generated by `automake`, i.e. have some `tests_single_SOURCES` variables, etc.

**Comment by zvr** [comment]
Very briefly:

- #186 will simply add more targets to the makefile (`Makefile.am` in our case)
- the location of the `build-recorder` executable should be inherited from the top-level Makefile
- the tests should be the compilations, as they are currently
- don't be confused that the test/benchmarking task is a compilation; this is not something that `automake` should change
- (maybe not even use `_SOURCES`, if this implies compilation)

**Comment by fvalasiad** [comment]
@zvr Autotools generally have a test suite, using the `TESTS` variable, have it point to a script.

Do we have any reason not to use it? In the past we spoke about how to test build recorder's correctness, and we concluded that using standard scripts and `grep` would be enough. Do we have any reason not to just create a script that runs the test cases and also test their output?
`test/tests.sh`
```
#!/bin/bash


build_recorder=$(../build-recorder)

$build_recorder -o compile_single_file.out $(CC) f1.c
# Test compile_single_file.out
```
...

Toplevel Makefile.am:
```
TESTS = test/tests.sh
```

and to run the tests:
```
make check
```

**Comment by fvalasiad** [comment]
@zvr If not the above then I don't know... using `_SOURCES` doesn't really work all that well. Make tries to premature compile the targets specified in _SOURCES and those builds aren't traced by `build-recorder`.

As far as I can tell automake simplifies the whole process when the targets are executables that need to be built & linked. This isn't the case in our scenario. Does automake offer some other functionality I haven't taken into consideration that makes it a superior option to a simple Makefile or to the test suite included in autotools?

**Comment by fvalasiad** [comment]
Closing this as it's no longer relevant.

**Pull request closed without merging**
