### PR TITLE
configure.ac: Check everything.

### LINKED ISSUE #177: configure should check everything
The autoconf-generated `configure` script should check everything being used in the code and correspondingly set preprocessor variables in the form of `HAVE_xxx` to `0` or `1`. The code then should use these to isolate parts that are not relevant.

The "everything used" list includes:

- header files being included
- preprocessor symbols being used
- functions being called

### PR DESCRIPTION
**Pull request by fvalasiad**
Closes #177

### CODE REVIEW

**Review by zvr — CHANGES_REQUESTED** [review]
I think this is a little overboard, since we're only talking about Linux systems for now...

Anyway, the only harm is increasing the `./configure` run time, so let's have it.

But please sort everything alphabetically!

**Comment by fvalasiad** [comment]
I took the issue's title literally!

**Review by zvr — APPROVED** [review]
Of course #177 talks about using the outcome of the tests to modify the code, but this can come at a later stage.

I mean, not everything should be an error if it's missing. For example `#if HAVE_MMAP ... mmap()`

**Comment by fvalasiad** [comment]
> Of course #177 talks about using the outcome of the tests to modify the code, but this can come at a later stage.
> 
> I mean, not everything should be an error if it's missing. For example `#if HAVE_MMAP ... mmap()`

Yep! I also thought about that! But as you mentioned this can come at a later stage.

If someone tries to build it and faces issues, we will be there and deal with em by introducing additional checks if necessary.

**Comment by fvalasiad** [comment]
@zvr Also, what do I go for next? Open an appropriate issue or pinpoint one of my own so I know what to target next and avoid working on PRs that won't be merged anytime soon.

**Pull request merged**
